config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'sessions#home'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/document', to: 'sessions#doc'
  get '/about', to: 'sessions#about'


  resources :users
  resources :posts, except: [:index] do
  	resources :comments, only: [:create] do

  	end
  end

  resources :categories

  resources :doc_types do
    resources :docs, except: [:show]
  end

end

app/controllers/doc_types_controller.rb
class DocTypesController < ApplicationController
	before_action :find_category, only: [:show, :edit, :update, :destroy]
	before_action :require_user, only: [:show, :index]
	before_action :require_admin, except: [:index, :show] 

	def index
		@doc_types = DocType.all
	end
	def show
		@doc_type = DocType.find(params[:id])
		@docs = @doc_type.docs.all
	end

	def new
		@doc_type = DocType.new
	end

	def create
		@doc_type = DocType.new(doc_type_params)

		if @doc_type.save
			flash[:notice] = "The category was created successfully"
			redirect_to doc_types_path
		else
			render :new
		end
	end

	def edit; end

	def update 
		if @doc_type.update(doc_type_params)
			flash[:notice] = "The category was updated successfully"
			redirect_to doc_types_path
		else
			render :edit
		end
	end

	def destroy
		@doc_type.destroy
		flash[:notice] = "The category was deleted successfully"
		redirect_to doc_types_path
	end

	def doc_type_params
		params.require(:doc_type).permit(:name)
	end

	def find_category
		@doc_type = DocType.find(params[:id])
	end 
end

app/views/doc_types/_form.html.erb
<%= render 'shared/error', obj: @doc_type %>
<%= form_for @doc_type do |dtype| %>
	<div class='control-group'>
		<%= dtype.label :name %>
		<%= dtype.text_field :name %>
	</div>
	<%= dtype.submit(@doc_type.new_record? ? "Create Document Category" : "Update Document Category"  , class: 'btn btn-success' )%>
<% end %>

app/views/doc_types/edit.html.erb
<%= render 'shared/title', title: "Edit Document Category" %>
<%= render 'form'%>

app/views/doc_types/index.html.erb
<%= render 'shared/title', title: "Community Document" %>

<div class='row'>
<% if logged_in? and current_user.admin?  %>
	<%= link_to "Create New Document Category", new_doc_type_path, class: 'btn btn-success'%>
<% end %>
</div>
<br/>
<div class='row'>
<% @doc_types.each do |dtype| %>
	<div class='well span7 inline'>
		<%= link_to dtype.name, doc_type_path(dtype), class: 'lead'%>
		
		<% if logged_in? and current_user.admin?  %>
			<%= link_to "Edit", edit_doc_type_path(dtype) %>
			<%= link_to 'Destroy',  dtype,  method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</div>
<% end %> 
</div>

app/views/doc_types/new.html.erb
<%= render 'shared/title', title: "New Document Category" %>
<%= render 'form'%>

app/views/doc_types/show.html.erb
<% header = (link_to("Document", doc_types_path) + "&raquo; #{@doc_type.name}".html_safe)%>
<%= render 'shared/title', title: header %>
  <div class='row'>
  	<% if logged_in? and current_user.admin?  %>
   		 <%= link_to 'New Document', new_doc_type_doc_path(@doc_type, @doc), class: 'btn btn-success btn-small' %>
   	<% end %>
  </div>
<br/>
<% @docs.each do |doc| %>
		<%= render 'docs/doc', doc: doc, doc_type: @doc_type %>
<% end %>