config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'sessions#home'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/document', to: 'sessions#doc'
  get '/about', to: 'sessions#about'


  resources :users
  resources :posts, except: [:index] do
  	resources :comments, only: [:create] do

  	end
  end

  resources :categories

  resources :doc_types do
    resources :docs, except: [:show]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :post_categories
	has_many :categories, through: :post_categories


	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :new, :create]
  before_action :require_creator, only: [:edit, :update, :destroy]

  def show 

    @comments = @post.comments.all.sort
    @comment = Comment.new
  end
  def new 
  	@post = Post.new
    
  end

  def create 
  	@post = Post.new(post_params)
  	@post.user = current_user

  	if @post.save
  		flash[:notice] = "Post created successfully"
  		redirect_to posts_path

  	else
  		render new_post_path
  	end
  end

  def edit 

  end

  def update

  	if @post.update(post_params)
  		flash[:notice] = "Post created successfully"
  		redirect_to posts_path

  	else
  		render :update
  	end
  end
  def vote
    @vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = 'You can only vote on a post once.'
        end
        redirect_to :back
      end
      format.js
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end
  def require_creator
    access_denied unless logged_in? && (current_user == @post.user || current_user.admin?)
  end

  def post_params
  	params.require(:post).permit!
  end
end

app/views/posts/_form.html.erb
<div class="well">
	<%= render 'shared/error', obj: @post %>
	<%= form_for @post do |f| %>
		<div class='control-group'>	
			<%= f.label :title, "Title" %>
			<%= f.text_field :title %>
		</div>
		<div class='control-group'>
			<%= f.label :description, "Description" %>
			<%= f.text_area :description, size: "20x6" %>
		</div>
		<div class='control-group'>
			<%= f.label :categories,  "Categories" %>
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
				<% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
			<% end %>
		</div>
		<%= f.submit(@post.new_record? ? "Create Post" : "Update Post", class: "btn btn-primary") %>
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
	<div class="span8 well">
		<h4><%= link_to(post.title, post_path(post)) %></h4>
		<p><%= post.description %></p>
		
		<p>
			<span class="quiet">posted by </span><%= post.user.username %>
			<small>at <%= display_datetime(post.created_at) %></small>
		</p>

		<p>
			<small>

				<span>
					<%= link_to("#{post.comments.size} comments", post_path(post)) %>
				</span>		

			</small>
		</p>
		<% if logged_in? and current_user == post.user %>
			<%= link_to("Edit", edit_post_path(post)) %>
			<%= link_to 'Destroy',  post,  method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>

	</div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/title', title: "Edit post" %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/title', title: "Community Forum" %>

app/views/posts/new.html.erb
<%= render 'shared/title', title: "Create a post" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'shared/title', title: @post.title %>
<p><%= @post.description %></p>
<p>
	<span class="quiet">posted by </span><%= @post.user.username %>
	<small>at <%= display_datetime(@post.created_at) %></small>
</p>
<hr/>

<% if logged_in? %>
	<%= render 'comments/form'%>
<% end %>

<h5>Comments:</h5>

<% @comments.each do |com| %>
	<%= render 'comments/comment', com: com %>
<% end %>