config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'sessions#home'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/document', to: 'sessions#doc'
  get '/about', to: 'sessions#about'


  resources :users
  resources :posts, except: [:index] do
  	resources :comments, only: [:create] do

  	end
  end

  resources :categories

  resources :doc_types do
    resources :docs, except: [:show]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_categories
	has_many :posts, through: :post_categories

	validates :name, presence: true, uniqueness: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :find_category, only: [:show, :edit, :update, :destroy]
	before_action :require_user, only: [:show, :index, :new, :create]
  	before_action :require_creator, only: [:edit, :update, :destroy]
	
	def index
		@categories = Category.all
	end
	def show
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			flash[:notice] = "The category was created successfully"
			redirect_to categories_path
		else
			render :new
		end
	end

	def edit; end

	def update 
		if @category.update(category_params)
			flash[:notice] = "The category was updated successfully"
			redirect_to root_path
		else
			render :edit
		end
	end

	def destroy
		@category.destroy
		flash[:notice] = "The category was deleted successfully"
		redirect_to categories_path

	end

	def category_params
		params.require(:category).permit(:name)
	end

	def find_category
		@category = Category.find(params[:id])
	end
	def require_creator
    	access_denied unless logged_in? && (current_user == @category.user || current_user.admin?)
  	end

end

app/views/categories/_category.html.erb
<%= render 'shared/error', obj: @category %>
<%= form_for @category do |cat| %>
	<div class='control-group'>
		<%= cat.label :name %>
		<%= cat.text_field :name %>
	</div>
	<%= cat.submit(@category.new_record? ? "Create Category" : "Update Category"  , class: 'btn btn-success' )%>
<% end %>

app/views/categories/edit.html.erb
<%= render 'shared/title', title: "Edit Category" %>
<%= render 'category'%>

app/views/categories/index.html.erb
<%= render 'shared/title', title: "Community Forum" %>

<div class='row'>
	<%= link_to "Create New Category", new_category_path, class: 'btn btn-success'%>
</div>
<br/>
<div class='row'>
<% @categories.each do |cat| %>
	<div class='well span7 inline'>
		<%= link_to cat.name, category_path(cat), class: 'lead'%>
		
		<% if logged_in? and current_user.admin?  %>
			<%= link_to "Edit", edit_category_path(cat) %>
			<%= link_to 'Destroy',  cat,  method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</div>
<% end %> 
</div>

app/views/categories/new.html.erb
<%= render 'shared/title', title: "Create Category" %>
<%= render 'category'%>

app/views/categories/show.html.erb
<% header = (link_to("All Posts", categories_path) + "&raquo; #{@category.name}".html_safe)%>
<%= render 'shared/title', title: header %>
  <div class='row'>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
  </div>
<br/>
<% @category.posts.each do |post| %>
		<%= render 'posts/post', post: post %>
<% end %>