config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'sessions#home'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/document', to: 'sessions#doc'
  get '/about', to: 'sessions#about'


  resources :users
  resources :posts, except: [:index] do
  	resources :comments, only: [:create] do

  	end
  end

  resources :categories

  resources :doc_types do
    resources :docs, except: [:show]
  end

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "WCLA", root_path, :class => 'brand' %>
  </li>
    <li>
    <%= link_to 'About', about_path %>
  </li>
  <li>
    <%= link_to 'Residents', users_path %>
  </li>
   <li>
    <%= link_to 'Documents', doc_types_path %>
  </li>
   <li>
    <%= link_to 'Community Forum', categories_path %>
  </li>
</ul>

<% if logged_in? %>
  <div class='btn-group nav_item'>
    <%= link_to('#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown') do %>
      <%= current_user.username %>
      <span class='caret'></span>
    <% end %>
    <ul class="dropdown-menu">
      <li>
        <%= link_to(edit_user_path(current_user)) do %>
          <i class='icon-pencil'></i>
          edit profile
        <% end %>
      </li>
      <li>
        <%= link_to(user_path(current_user)) do %>
          <i class='icon-user'></i>
          view profile
        <% end %>
      </li>
      <li>
        <%= link_to(logout_path) do %>
          <i class='icon-circle-arrow-left'></i>
          logout
        <% end %>
      </li>
    </ul>
  </div>
<% else # logged out%>
  <div class='nav_item'>
    <%= link_to 'Register', register_path, class: 'btn btn-small btn-success' %>
  </div>
  <div class='nav_item'>
    <%= link_to 'Login', login_path, class: 'btn btn-small' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>